import {
  Activity,
  ArrowRight,
  ArrowUpRight,
  Award,
  BadgeCheck,
  Beaker,
  Bot,
  Boxes,
  BrainCircuit,
  Briefcase,
  Building2,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  ClipboardList,
  Clock,
  Cog,
  Compass,
  Cpu,
  Database,
  ExternalLink,
  Factory,
  FileCheck,
  FlaskConical,
  Gauge,
  GraduationCap,
  Globe,
  Handshake,
  HardHat,
  Headphones,
  Heart,
  Info,
  Eye,
  LayoutGrid,
  CircleHelp,
  PlusCircle,
  Recycle,
  Search,
  UserRound,
  Landmark,
  Layers,
  Leaf,
  Lightbulb,
  Loader2,
  Mail,
  MapPin,
  Maximize2,
  Menu,
  Network,
  Orbit,
  Package,
  PencilRuler,
  Phone,
  RefreshCw,
  Rocket,
  Scale,
  ScanEye,
  ShieldCheck,
  Ship,
  Snowflake,
  Sparkles,
  Sprout,
  Target,
  TrendingUp,
  Truck,
  TriangleAlert,
  Users,
  Wheat,
  Workflow,
  Wrench,
  X,
  Play,
  FileText,
  Share2,
  Download,
  Newspaper,
  Volume2,
  type LucideIcon,
} from "lucide-react";

/**
 * Central icon registry. Data files reference icons by string key so the
 * same records can later come from the database. Lucide is the ONLY icon
 * system used across the site (Section 40A).
 */
export const iconMap: Record<string, LucideIcon> = {
  activity: Activity,
  "arrow-right": ArrowRight,
  "arrow-up-right": ArrowUpRight,
  award: Award,
  "badge-check": BadgeCheck,
  beaker: Beaker,
  bot: Bot,
  boxes: Boxes,
  "brain-circuit": BrainCircuit,
  briefcase: Briefcase,
  "building-2": Building2,
  check: Check,
  eye: Eye,
  "grid-3x3": LayoutGrid,
  headphones: Headphones,
  heart: Heart,
  "help-circle": CircleHelp,
  "plus-circle": PlusCircle,
  recycle: Recycle,
  search: Search,
  "user-round": UserRound,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "clipboard-list": ClipboardList,
  clock: Clock,
  cog: Cog,
  compass: Compass,
  cpu: Cpu,
  database: Database,
  "external-link": ExternalLink,
  factory: Factory,
  "file-check": FileCheck,
  "flask-conical": FlaskConical,
  gauge: Gauge,
  "graduation-cap": GraduationCap,
  globe: Globe,
  handshake: Handshake,
  "hard-hat": HardHat,
  info: Info,
  landmark: Landmark,
  layers: Layers,
  leaf: Leaf,
  lightbulb: Lightbulb,
  "loader-2": Loader2,
  mail: Mail,
  "map-pin": MapPin,
  "maximize-2": Maximize2,
  menu: Menu,
  network: Network,
  orbit: Orbit,
  package: Package,
  "pencil-ruler": PencilRuler,
  phone: Phone,
  "refresh-cw": RefreshCw,
  rocket: Rocket,
  scale: Scale,
  "scan-eye": ScanEye,
  "shield-check": ShieldCheck,
  ship: Ship,
  snowflake: Snowflake,
  sparkles: Sparkles,
  sprout: Sprout,
  target: Target,
  "trending-up": TrendingUp,
  truck: Truck,
  "triangle-alert": TriangleAlert,
  users: Users,
  wheat: Wheat,
  workflow: Workflow,
  wrench: Wrench,
  x: X,
  play: Play,
  "file-text": FileText,
  "share-2": Share2,
  download: Download,
  newspaper: Newspaper,
  "volume-2": Volume2,
};

export interface IconProps extends React.SVGProps<SVGSVGElement> {
  name: string;
}

export function Icon({ name, ...props }: IconProps) {
  const Cmp = iconMap[name] ?? Info;
  return <Cmp {...props} />;
}
